In [1]:
import numpy as np

In [1]:
print("hello MLP")

hello MLP


In [4]:
a=np.array([5,2,3,4])    # print array
print(a)
a=np.array([5,2,3,4])
print(a)

[5 2 3 4]
[5 2 3 4]


In [6]:
print("array :",a)
print(f"array a(a)")
print("array a:{}".format(a))

array : [5 2 3 4]
array a(a)
array a:[5 2 3 4]


In [7]:
print(f"ndim:{a.ndim}")    #print min of array
print(f"size:{a.size}")   # print size of array
print(f"shape:{a.shape}")   # print shape
print(f"stype:{a.dtype}")     # type of array
print(f"itemsize{a.itemsize}")   # number of element in array

print("min",a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.itemsize)

ndim:1
size:4
shape:(4,)
stype:int32
itemsize4
min 1
4
(4,)
int32
4


In [14]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [16]:
b=np.array([4,5,6,7])
c=np.add(a,b)     # print addition of two array
print(c)

print(np.add(a,b))

[ 5  7  9 11]
[ 5  7  9 11]


In [8]:
b=np.array([4,5,6,7])
c=np.multiply(a,b)     # print multiplication of two array
print(c)

[ 4 10 18 28]


In [9]:
b=np.array([4,5,6,7])
c=np.divide(a,b)       #print division of two array
print(c)

[0.25       0.4        0.5        0.57142857]


In [10]:
b=np.array([4,5,6,7])
c=np.subtract(a,b)              #print subtraction of two array
print(c)

[-3 -3 -3 -3]


In [10]:
b=np.array([4,5,6,7])
c=np.power(a,b)               # print reminder of a two array
print(c)

[  625    32   729 16384]


In [8]:
b=np.array([4,5,6,7])
c=np.abs(a,b)                 #print absolute of two array
print(c)

[5 2 3 4]


In [52]:
b=np.array([4,5,6,7])
c=np.mod(a,b)         #print modulo of array
print(c)

[1 2 3 4]


In [15]:
e=np.array(['mansi','liza'])     #print array
print(e)

['mansi' 'liza']


In [17]:
z=np.zeros((2,3))             # print array that contain zero
print(z)

z=np.zeros([3,4])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
one=np.ones((3,3))           # print array that contain only one
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
empty=np.empty((2,2))
print(empty)

[[2.12199579e-314 4.67296746e-307]
 [5.43472210e-321 7.21478569e-312]]


In [27]:
a=np.array([[2,3,5],[5,6,7]])
print(a)
sliced_arr=a[1,2]                #print the element of given index
print(sliced_arr)

ab=a[1,1]
print(ab)

[[2 3 5]
 [5 6 7]]
7
6


In [37]:
indexed_arr=a[[1,0],[0,1]]          # print index of array
print(indexed_arr,"indexed")

ar=a[[1,1],[0,1]]
print(ar)

[5 3] indexed
[5 6]


In [38]:
print(a.sum())               # print the sum of element in the array

28


In [3]:
a1=np.array([25,45,50])
print(np.sqrt(a1))              #print the squre of element in the array

[5.         6.70820393 7.07106781]


In [6]:
e=np.size(['mansi','vraj','liza'])          # print the size of array
print(e)

3


In [14]:
a=np.array([1,2,3,4])
print(a)        


[1 2 3 4]


In [17]:
b=a+5
print(b)                        #add value in the array

[6 7 8 9]


In [36]:
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m2=np.array([[6,2,3],[4,5,6],[7,8,9]])      # dot use for matrix multiplication
m3=np.dot(m1,m2)
print(m3)

[[ 35  36  42]
 [ 86  81  96]
 [137 126 150]]


In [22]:
bool=np.array([[True,True,False],[False,True,True]])
print("all() with axis none",np.all(bool))          # for and opration all function  
print("all() with axis=0",np.all(bool,axis=0))           # zero means column
print("all() with axis=0",np.all(bool,axis=1))           # one means row

all() with axis none False
all() with axis=0 [False  True False]
all() with axis=0 [False False]


In [23]:
bool=np.array([[True,True,False],[False,True,True]])
print("all() with axis none",np.any(bool))           # for or opration any function
print("all() with axis=0",np.any(bool,axis=0))
print("all() with axis=0",np.any(bool,axis=1))

all() with axis none True
all() with axis=0 [ True  True  True]
all() with axis=0 [ True  True]


In [40]:
a1=np.arange(8)
print(a1)                    # arange the array  in sequence with given number
re=a1.reshape(2,4)           #reshape the array
print(re)
re=a.reshape(2,2)
print(re)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[5 2]
 [3 4]]


In [47]:
print(m1)
print(m2)
print(m3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [44]:
h=np.hstack((m1,m2,m3))          # horizontal stack
print(h)

[[  1   2   3   6   2   3  35  36  42]
 [  4   5   6   4   5   6  86  81  96]
 [  7   8   9   7   8   9 137 126 150]]


In [45]:
vsplit=np.vsplit(h,3)
print(vsplit)                     # split array vertically

[array([[ 1,  2,  3,  6,  2,  3, 35, 36, 42]]), array([[ 4,  5,  6,  4,  5,  6, 86, 81, 96]]), array([[  7,   8,   9,   7,   8,   9, 137, 126, 150]])]


In [31]:
hsplit=np.hsplit(h,3)
print(hsplit)                               # split the array horizontally

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])]


In [35]:
arr=np.array([23,45,67,89])
print("sqrt",np.sqrt(arr))  # return the squre
print("exp",np.exp(arr))   # return the expontential of each element
print("sin",np.sin(arr))   # return the sin of element
print("cos",np.cos(arr))   # return the cos of element
print("log",np.log(arr))   # return the log of element
print("sum",np.sum(arr))   # return the sum ofelement in the array
print("std",np.std(arr))   # return the standard division of element

sqrt [4.79583152 6.70820393 8.18535277 9.43398113]
exp [9.74480345e+09 3.49342711e+19 1.25236317e+29 4.48961282e+38]
sin [-0.8462204   0.85090352 -0.85551998  0.86006941]
cos [-0.53283302  0.52532199 -0.5177698   0.51017704]
log [3.13549422 3.80666249 4.20469262 4.48863637]
sum 224
std 24.596747752497688


In [50]:
print("random: {}\n".format(np.random.random(20)))          # print random value
print("rand : {}\n".format(np.random.rand(3,5)))
print("randint : {}\n".format(np.random.randint(0,100,20)))
print(np.random.permutation(np.arange(10))) 

random: [0.71279688 0.1339438  0.76579213 0.0455691  0.97525465 0.27124508
 0.59154435 0.21227637 0.99156198 0.29129941 0.03246611 0.84602582
 0.40041443 0.53129695 0.3790575  0.09896649 0.82963214 0.81928482
 0.84060861 0.71362054]

rand : [[0.48114524 0.21471756 0.64713049 0.44012096 0.02249865]
 [0.85562186 0.31711321 0.74384622 0.23890327 0.98183409]
 [0.7460596  0.98785778 0.355018   0.57495394 0.60890409]]

randint : [ 2 87 54  2 22 40 42 23 78 54 96 45 37 79 44 20 31 74 72 66]

[5 6 2 7 1 0 8 4 3 9]
